In [1]:
!pip install undetected-chromedriver

Collecting undetected-chromedriver
  Downloading undetected-chromedriver-3.5.5.tar.gz (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 KB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting selenium>=4.9.0
  Downloading selenium-4.36.0-py3-none-any.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 4.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: requests in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from undetected-chromedriver) (2.32.5)
Collecting websockets
  Downloading websockets-15.0.1-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.3/173.3 KB 5.9 MB/s eta 0:00:00
Collecting websocket-client<2.0,>=1.8.0
  Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Collecting trio-websocket<1.0,>=0.12.2
  Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Collecting trio<1.0,>=0.30.0
  Downloading trio-0.31.0-py3-none-any.whl (512 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.7/512.7 KB 1.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: certifi>=2025.6.15 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (2026.1.4)
Requirement already satisfied: urllib3[socks]<3.0,>=2.5.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (2.6.3)
Requirement already satisfied: typing_extensions<5.0,>=4.14.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests->undetected-chromedriver) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests->undetected-chromedriver) (3.11)
Collecting sniffio>=1.3.0
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: exceptiongroup in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio<1.0,>=0.30.0->selenium>=4.9.0->undetected-chromedriver) (1.3.1)
Requirement already satisfied: attrs>=23.2.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio<1.0,>=0.30.0->selenium>=4.9.0->undetected-chromedriver) (25.4.0)
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting h11<1,>=0.9.0
  Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using legacy 'setup.py install' for undetected-chromedriver, since package 'wheel' is not installed.
Installing collected packages: sortedcontainers, websockets, websocket-client, sniffio, pysocks, outcome, h11, wsproto, trio, trio-websocket, selenium, undetected-chromedriver
  Running setup.py install for undetected-chromedriver ... done
Successfully installed h11-0.16.0 outcome-1.3.0.post0 pysocks-1.7.1 selenium-4.36.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.31.0 trio-websocket-0.12.2 undetected-chromedriver-3.5.5 websocket-client-1.9.0 websockets-15.0.1 wsproto-1.2.0
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/bin/python3.9 -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
import undetected_chromedriver as uc

from bs4 import BeautifulSoup

In [ ]:
driver = uc.Chrome(version_main=144)

In [ ]:
pip install -U undetected-chromedriver

Requirement already satisfied: undetected-chromedriver in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (3.5.5)
Requirement already satisfied: selenium>=4.9.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from undetected-chromedriver) (4.36.0)
Requirement already satisfied: requests in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from undetected-chromedriver) (2.32.5)
Requirement already satisfied: websockets in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from undetected-chromedriver) (15.0.1)
Requirement already satisfied: urllib3[socks]<3.0,>=2.5.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (2.6.3)
Requirement already satisfied: typing_extensions<5.0,>=4.14.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (4.15.0)
Requirement already satisfied: trio<1.0,>=0.30.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (0.31.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (1.9.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (0.12.2)
Requirement already satisfied: certifi>=2025.6.15 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from selenium>=4.9.0->undetected-chromedriver) (2026.1.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests->undetected-chromedriver) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from requests->undetected-chromedriver) (3.11)
Requirement already satisfied: exceptiongroup in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio<1.0,>=0.30.0->selenium>=4.9.0->undetected-chromedriver) (1.3.1)
Requirement already satisfied: sortedcontainers in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio<1.0,>=0.30.0->selenium>=4.9.0->undetected-chromedriver) (2.4.0)
Requirement already satisfied: attrs>=23.2.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio<1.0,>=0.30.0->selenium>=4.9.0->undetected-chromedriver) (25.4.0)
Requirement already satisfied: outcome in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio<1.0,>=0.30.0->selenium>=4.9.0->undetected-chromedriver) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio<1.0,>=0.30.0->selenium>=4.9.0->undetected-chromedriver) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium>=4.9.0->undetected-chromedriver) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver) (0.16.0)
WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [11]:
driver.get("https://fbref.com/en/comps/8/2023-2024/2023-2024-Champions-League-Stats")

In [13]:
from io import StringIO

In [15]:
df = pd.read_html(driver.page_source, attrs={"id": "stats_squads_standard_for"})[0]

/var/folders/rm/8sf3dfrx23n5yr19qhb9648w0000gn/T/ipykernel_74013/1815874445.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(driver.page_source, attrs={"id": "stats_squads_standard_for"})[0]

In [16]:
df.head()

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Squad               # Pl                Age
0          be Antwerp                 20               24.5
1         eng Arsenal                 23               25.2
2  es Atlético Madrid                 22               29.4
3        es Barcelona                 25               26.5
4    de Bayern Munich                 23               27.6

  Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                Poss           MP Starts   Min   90s         Gls Ast  ...
0               43.2            6     66   540   6.0           6   4  ...
1               56.5           10    110   930  10.3          19  16  ...
2               49.1           10    110   930  10.3          20  11  ...
3               54.2           10    110   900  10.0          19  18  ...
4               54.4           12    132  1080  12.0          21  16  ...

                          Per 90 Minutes
  G-PK PK PKatt CrdY CrdR            Gls   Ast   G+A  G-PK G+A-PK
0    6  0     1   15    2           1.00  0.67  1.67  1.00   1.67
1   18  1     1   13    0           1.84  1.55  3.39  1.74   3.29
2   20  0     1   25    1           1.94  1.06  3.00  1.94   3.00
3   19  0     0   30    2           1.90  1.80  3.70  1.90   3.70
4   18  3     3   15    1           1.75  1.33  3.08  1.50   2.83

[5 rows x 21 columns]

In [17]:
df.columns = ['_'.join(col).strip() for col in df.columns.values]

In [18]:
df.head()

,Unnamed: 0_level_0_Squad,Unnamed: 1_level_0_# Pl,Unnamed: 2_level_0_Age,Unnamed: 3_level_0_Poss,Playing Time_MP,Playing Time_Starts,Playing Time_Min,Playing Time_90s,Performance_Gls,Performance_Ast,...,Performance_G-PK,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK
0,be Antwerp,20,24.5,43.2,6,66,540,6.0,6,4,...,6,0,1,15,2,1.00,0.67,1.67,1.00,1.67
1,eng Arsenal,23,25.2,56.5,10,110,930,10.3,19,16,...,18,1,1,13,0,1.84,1.55,3.39,1.74,3.29
2,es Atlético Madrid,22,29.4,49.1,10,110,930,10.3,20,11,...,20,0,1,25,1,1.94,1.06,3.00,1.94,3.00
3,es Barcelona,25,26.5,54.2,10,110,900,10.0,19,18,...,19,0,0,30,2,1.90,1.80,3.70,1.90,3.70
4,de Bayern Munich,23,27.6,54.4,12,132,1080,12.0,21,16,...,18,3,3,15,1,1.75,1.33,3.08,1.50,2.83

In [19]:
player_stats = pd.read_html(driver.page_source, attrs={"id": "stats_standard"})[0]
player_stats.columns = ['_'.join(col).strip() for col in player_stats.columns.values]

player_stats.head()

/var/folders/rm/8sf3dfrx23n5yr19qhb9648w0000gn/T/ipykernel_74013/787434050.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player_stats = pd.read_html(driver.page_source, attrs={"id": "stats_standard"})[0]

,Unnamed: 0_level_0_Rk,Unnamed: 1_level_0_Player,Unnamed: 2_level_0_Nation,Unnamed: 3_level_0_Pos,Unnamed: 4_level_0_Squad,Unnamed: 5_level_0_Age,Unnamed: 6_level_0_Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK,Unnamed: 24_level_0_Matches
0,1,Patrick van Aanholt,nl NED,"DF,MF",nl PSV,32,1990,2,1,99,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
1,2,Brenden Aaronson,us USA,MF,de Union Berlin,22,2000,6,1,137,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
2,3,Salis Abdul Samed,gh GHA,MF,fr Lens,23,2000,6,6,495,...,0,0,2,0,0.00,0.00,0.00,0.00,0.00,Matches
3,4,Francesco Acerbi,it ITA,DF,it Inter,35,1988,6,4,423,...,0,0,1,0,0.00,0.21,0.21,0.00,0.21,Matches
4,5,Elias Achouri,tn TUN,"FW,MF",dk FC Copenhagen,24,1999,8,7,552,...,0,0,0,0,0.00,0.16,0.16,0.00,0.16,Matches