In [3]:
from statsbombpy import sb

In [4]:
sb.competitions()

/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2025-07-28T14:19:20.467348,2025-07-29T16:03:07.355174,2025-07-29T16:03:07.355174,2025-07-28T14:19:20.467348
72,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
73,72,107,International,Women's World Cup,female,False,True,2023,2025-07-14T10:07:06.620906,2025-07-14T10:10:27.224586,2025-07-14T10:10:27.224586,2025-07-14T10:07:06.620906
74,72,30,International,Women's World Cup,female,False,True,2019,2024-08-08T15:57:56.748740,2021-06-13T16:17:31.694,None,2024-08-08T15:57:56.748740

In [5]:
sb.matches(competition_id=1267, season_id=107)

/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3923881,2024-02-11,22:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Côte d'Ivoire,1,2,available,...,None,8,Final,Stade Olympique Alassane Ouattara,Dahane Beida,José Vítor dos Santos Peseiro,Emerse Faé,1.1.0,2,2
1,3923880,2024-02-10,22:00:00.000,Africa - African Cup of Nations,2023,South Africa,Congo DR,0,0,available,...,None,7,3rd Place Final,Stade Félix Houphouët-Boigny,Bamlak Tessema Weyesa,Hugo Henri Broos,Sébastien Desabre,1.1.0,2,2
2,3922838,2024-02-07,22:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Congo DR,1,0,available,...,None,6,Semi-finals,Stade Olympique Alassane Ouattara,Ibrahim Mutaz,Emerse Faé,Sébastien Desabre,1.1.0,2,2
3,3922837,2024-02-07,19:00:00.000,Africa - African Cup of Nations,2023,Nigeria,South Africa,1,1,available,...,None,6,Semi-finals,Stade de Bouaké,Amin Mohamed Omar,José Vítor dos Santos Peseiro,Hugo Henri Broos,1.1.0,2,2
4,3922242,2024-01-29,22:00:00.000,Africa - African Cup of Nations,2023,Senegal,Côte d'Ivoire,1,1,available,...,None,4,Round of 16,Stade Charles Konan Banny de Yamoussoukro,Pierre Ghislain Atcho,Aliou Cissé,Emerse Faé,1.1.0,2,2
5,3922239,2024-01-28,19:00:00.000,Africa - African Cup of Nations,2023,Equatorial Guinea,Guinea,0,1,available,...,None,4,Round of 16,Stade Olympique Alassane Ouattara,Omar Abdulkadir Artan,Juan Micha Obiang Bicogo,Kaba Diawara,1.1.0,2,2
6,3922659,2024-02-03,19:00:00.000,Africa - African Cup of Nations,2023,Mali,Côte d'Ivoire,1,2,available,...,None,5,Quarter-finals,Stade de Bouaké,Mohamed Adel Elsaid,Éric Chelle,Emerse Faé,1.1.0,2,2
7,3922658,2024-02-03,22:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,South Africa,0,0,available,...,None,5,Quarter-finals,Stade Charles Konan Banny de Yamoussoukro,Jean Jacques Ndala Ngambo,Pedro Leitão Brito,Hugo Henri Broos,1.1.0,2,2
8,3922244,2024-01-30,19:00:00.000,Africa - African Cup of Nations,2023,Mali,Burkina Faso,2,1,available,...,None,4,Round of 16,Stade Amadou Gon Coulibaly,Ibrahim Mutaz,Éric Chelle,Hubert Velud,1.1.0,2,2
9,3922356,2024-02-02,22:00:00.000,Africa - African Cup of Nations,2023,Congo DR,Guinea,3,1,available,...,None,5,Quarter-finals,Stade Olympique Alassane Ouattara,Mustapha Ghorbal,Sébastien Desabre,Kaba Diawara,1.1.0,2,2
10,3922321,2024-02-02,19:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Angola,1,0,available,...,None,5,Quarter-finals,Stade Félix Houphouët-Boigny,Issa Sy,José Vítor dos Santos Peseiro,Pedro Valdemar Soares Gonçalves,1.1.0,2,2
11,3922237,2024-01-27,19:00:00.000,Africa - African Cup of Nations,2023,Angola,Namibia,3,0,available,...,None,4,Round of 16,Stade de Bouaké,Dahane Beida,Pedro Valdemar Soares Gonçalves,Collin Benjamin,1.1.0,2,2
12,3922243,2024-01-30,22:00:00.000,Africa - African Cup of Nations,2023,Morocco,South Africa,0,2,available,...,None,4,Round of 16,Stade Laurent Pokou,Mahmood Ali Mahmood Ismail,Walid Regragui,Hugo Henri Broos,1.1.0,2,2
13,3922241,2024-01-29,19:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Mauritania,1,0,available,...,None,4,Round of 16,Stade Félix Houphouët-Boigny,Mohamed Adel Elsaid,Pedro Leitão Brito,Amir Abdou,1.1.0,2,2
14,3922240,2024-01-28,22:00:00.000,Africa - African Cup of Nations,2023,Egypt,Congo DR,1,1,available,...,None,4,Round of 16,Stade Laurent Pokou,Abongile Tom,Rui Carlos Pinho da Vitória,Sébastien Desabre,1.1.0,2,2
15,3922238,2024-01-27,22:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Cameroon,2,0,available,...,None,4,Round of 16,Stade Félix Houphouët-Boigny,Redouane Jiyed,José Vítor dos Santos Peseiro,Rigobert Song Bahanag,1.1.0,2,2
16,3920396,2024-01-18,22:00:00.000,Africa - African Cup of Nations,2023,Egypt,Ghana,2,2,available,...,None,2,Group Stage,Stade Félix Houphouët-Boigny,Pierre Ghislain Atcho,Rui Carlos Pinho da Vitória,Chris Hughton,1.1.0,2,2
17,3920386,2024-01-14,16:00:00.000,Africa - African Cup of Nations,2023,Nigeria,Equatorial Guinea,1,1,available,...,None,1,Group Stage,Stade Olympique Alassane Ouattara,Abongile Tom,José Vítor dos Santos Peseiro,Juan Micha Obiang Bicogo,1.1.0,2,2
18,3920385,2024-01-14,19:00:00.000,Africa - African Cup of Nations,2023,Egypt,Mozambique,2,2,available,...,None,1,Group Stage,Stade Félix Houphouët-Boigny,Dahane Beida,Rui Carlos Pinho da Vitória,Francisco Queriol Conde Júnior,1.1.0,2,2
19,3920387,2024-01-14,22:00:00.000,Africa - African Cup of Nations,2023,Ghana,Cape Verde Islands,1,2,available,...,None,1,Group Stage,Stade Félix Houphouët-Boigny,Jean Jacques Ndala Ngambo,Chris Hughton,Pedro Leitão Brito,1.1.0,2,2
20,3920419,2024-01-24,22:00:00.000,Africa - African Cup of Nations,2023,Zambia,Morocco,0,1,available,...,None,3,Group Stage,Stade Laurent Pokou,Patrice Tanguy Mebiame,Avraham Grant,Walid Regragui,1.1.0,2,2
21,3920418,2024-01-24,22:00:00.000,Africa - African Cup of Nations,2023,Tanzania,Congo DR,0,0,available,...,None,3,Group Stage,Stade Amadou Gon Coulibaly,Amin Mohamed Omar,Hemed Suleiman Ali,Sébastien Desabre,1.1.0,2,2
22,3920417,2024-01-24,19:00:00.000,Africa - African Cup of Nations,2023,Namibia,Mali,0,0,available,...,None,3,Group Stage,Stade Laurent Pokou,Samuel Uwikunda,Collin Benjamin,Éric Chelle,1.1.0,2,2
23,3920416,2024-01-24,19:00:00.000,Africa - African Cup of Nations,2023,South Africa,Tunisia,0,0,available,...,None,3,Group Stage,Stade Amadou Gon Coulibaly,Issa Sy,Hugo Henri Broos,Jalel Kadri,1.1.0,2,2
24,3920415,2024-01-23,22:00:00.000,Africa - African Cup of Nations,2023,Mauritania,Algeria,1,0,available,...,None,3,Group Stage,Stade de Bouaké,Omar Abdulkadir Artan,Amir Abdou,Djamel Belmadi,1.1.0,2,2
25,3920414,2024-01-23,22:00:00.000,Africa - African Cup of Nations,2023,Angola,Burkina Faso,2,0,available,...,None,3,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Jean Jacques Ndala Ngambo,Pedro Valdemar Soares Gonçalves,Hubert Velud,1.1.0,2,2
26,3920413,2024-01-23,19:00:00.000,Africa - African Cup of Nations,2023,Gambia,Cameroon,2,3,available,...,None,3,Group Stage,Stade de Bouaké,Bamlak Tessema Weyesa,Tom Saintfiet,Rigobert Song Bahanag,1.1.0,2,2
27,3920412,2024-01-23,19:00:00.000,Africa - African Cup of Nations,2023,Guinea,Senegal,0,2,available,...,None,3,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Pacifique Ndabihawenimana,Kaba Diawara,Aliou Cissé,1.1.0,2,2
28,3920411,2024-01-22,22:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Egypt,2,2,available,...,None,3,Group Stage,Stade Félix Houphouët-Boigny,Alhadi Allaou Mahamat,Pedro Leitão Brito,Rui Carlos Pinho da Vitória,1.1.0,2,2
29,3920410,2024-01-22,22:00:00.000,Africa - African Cup of Nations,2023,Mozambique,Ghana,2,2,available,...,None,3,Group Stage,Stade Olympique Alassane Ouattara,Ibrahim Mutaz,Francisco Queriol Conde Júnior,Chris Hughton,1.1.0,2,2
30,3920409,2024-01-22,19:00:00.000,Africa - African Cup of Nations,2023,Guinea-Bissau,Nigeria,0,1,available,...,None,3,Group Stage,Stade Félix Houphouët-Boigny,Bouchra Karboubi,Baciro Candé,José Vítor dos Santos Peseiro,1.1.0,2,2
31,3920408,2024-01-22,19:00:00.000,Africa - African Cup of Nations,2023,Equatorial Guinea,Côte d'Ivoire,4,0,available,...,None,3,Group Stage,Stade Olympique Alassane Ouattara,Mahmood Ali Mahmood Ismail,Juan Micha Obiang Bicogo,Jean-Louis Gasset,1.1.0,2,2
32,3920407,2024-01-21,22:00:00.000,Africa - African Cup of Nations,2023,South Africa,Namibia,4,0,available,...,None,2,Group Stage,Stade Amadou Gon Coulibaly,Youcef Gamouh,Hugo Henri Broos,Collin Benjamin,1.1.0,2,2
33,3920406,2024-01-21,19:00:00.000,Africa - African Cup of Nations,2023,Zambia,Tanzania,1,1,available,...,None,2,Group Stage,Stade Laurent Pokou,Djindo Louis Houngnandande,Avraham Grant,Adel Amrouche,1.1.0,2,2
34,3920405,2024-01-21,16:00:00.000,Africa - African Cup of Nations,2023,Morocco,Congo DR,1,1,available,...,None,2,Group Stage,Stade Laurent Pokou,Peter Waweru Kamaku,Walid Regragui,Sébastien Desabre,1.1.0,2,2
35,3920404,2024-01-20,22:00:00.000,Africa - African Cup of Nations,2023,Tunisia,Mali,1,1,available,...,None,2,Group Stage,Stade Amadou Gon Coulibaly,Daniel Nii Ayi Laryea,Jalel Kadri,Éric Chelle,1.1.0,2,2
36,3920403,2024-01-20,19:00:00.000,Africa - African Cup of Nations,2023,Mauritania,Angola,2,3,available,...,None,2,Group Stage,Stade de Bouaké,Mohamed Maarouf Eid Mansour,Amir Abdou,Pedro Valdemar Soares Gonçalves,1.1.0,2,2
37,3920402,2024-01-20,16:00:00.000,Africa - African Cup of Nations,2023,Algeria,Burkina Faso,2,2,available,...,None,2,Group Stage,Stade de Bouaké,Abongile Tom,Djamel Belmadi,Hubert Velud,1.1.0,2,2
38,3920401,2024-01-19,22:00:00.000,Africa - African Cup of Nations,2023,Guinea,Gambia,1,0,available,...,None,2,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Abdel Aziz Mohamed Bouh,Kaba Diawara,Tom Saintfiet,1.1.0,2,2
39,3920400,2024-01-19,19:00:00.000,Africa - African Cup of Nations,2023,Senegal,Cameroon,3,1,available,...,None,2,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Mahmood Ali Mahmood Ismail,Aliou Cissé,Rigobert Song Bahanag,1.1.0,2,2
40,3920399,2024-01-19,16:00:00.000,Africa - African Cup of Nations,2023,Cape Verde Islands,Mozambique,3,0,available,...,None,2,Group Stage,Stade Félix Houphouët-Boigny,Samir Guezzaz,Pedro Leitão Brito,Francisco Queriol Conde Júnior,1.1.0,2,2
41,3920398,2024-01-18,19:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Nigeria,0,1,available,...,None,2,Group Stage,Stade Olympique Alassane Ouattara,Mustapha Ghorbal,Jean-Louis Gasset,José Vítor dos Santos Peseiro,1.1.0,2,2
42,3920397,2024-01-18,16:00:00.000,Africa - African Cup of Nations,2023,Equatorial Guinea,Guinea-Bissau,4,2,available,...,None,2,Group Stage,Stade Olympique Alassane Ouattara,Samuel Uwikunda,Juan Micha Obiang Bicogo,Baciro Candé,1.1.0,2,2
43,3920395,2024-01-17,22:00:00.000,Africa - African Cup of Nations,2023,Congo DR,Zambia,1,1,available,...,None,1,Group Stage,Stade Laurent Pokou,Bamlak Tessema Weyesa,Sébastien Desabre,Avraham Grant,1.1.0,2,2
44,3920394,2024-01-17,19:00:00.000,Africa - African Cup of Nations,2023,Morocco,Tanzania,3,0,available,...,None,1,Group Stage,Stade Laurent Pokou,Alhadi Allaou Mahamat,Walid Regragui,Adel Amrouche,1.1.0,2,2
45,3920393,2024-01-16,19:00:00.000,Africa - African Cup of Nations,2023,Tunisia,Namibia,0,1,available,...,None,1,Group Stage,Stade Amadou Gon Coulibaly,Abdulkadir Artan,Jalel Kadri,Collin Benjamin,1.1.0,2,2
46,3920392,2024-01-16,16:00:00.000,Africa - African Cup of Nations,2023,Burkina Faso,Mauritania,1,0,available,...,None,1,Group Stage,Stade de Bouaké,Jalal Jayed,Hubert Velud,Amir Abdou,1.1.0,2,2
47,3920391,2024-01-16,22:00:00.000,Africa - African Cup of Nations,2023,Mali,South Africa,2,0,available,...,None,1,Group Stage,Stade Amadou Gon Coulibaly,Mohamed Adel Hussein,Éric Chelle,Hugo Henri Broos,1.1.0,2,2
48,3920390,2024-01-15,22:00:00.000,Africa - African Cup of Nations,2023,Algeria,Angola,1,1,available,...,None,1,Group Stage,Stade de Bouaké,Issa Sy,Djamel Belmadi,Pedro Valdemar Soares Gonçalves,1.1.0,2,2
49,3920389,2024-01-15,19:00:00.000,Africa - African Cup of Nations,2023,Cameroon,Guinea,1,1,available,...,None,1,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Ibrahim Mutaz,Rigobert Song Bahanag,Kaba Diawara,1.1.0,2,2
50,3920388,2024-01-15,16:00:00.000,Africa - African Cup of Nations,2023,Senegal,Gambia,3,0,available,...,None,1,Group Stage,Stade Charles Konan Banny de Yamoussoukro,Redouane Jiyed,Aliou Cissé,Tom Saintfiet,1.1.0,2,2
51,3920384,2024-01-13,22:00:00.000,Africa - African Cup of Nations,2023,Côte d'Ivoire,Guinea-Bissau,2,0,available,...,None,1,Group Stage,Stade Olympique Alassane Ouattara,Amin Mohamed Omar,Jean-Louis Gasset,Baciro Candé,1.1.0,2,2

In [7]:
sb.events(match_id=3923881).head(10)

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 343, 'lineup': [{'player': {'id'...",Nigeria,775,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Côte d'Ivoire,3374,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Côte d'Ivoire,3374,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Côte d'Ivoire,3374,00:00:00.000,Half Start,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:00.000,Half Start,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:00.663,Pass,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:03.081,Pass,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:06.561,Pass,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Nigeria,775,00:00:09.250,Pass,True

In [9]:
all_matches = []
for match_id in sb.matches(competition_id=1267, season_id=107).match_id:
    temp_match = sb.events(match_id=match_id)
    all_matches.append(temp_match)

all_matches

/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
/Users/mahamudulhasanmithhu/.pyenv/versions/3.9.13/lib/python3.9/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

[     50_50 bad_behaviour_card ball_receipt_outcome ball_recovery_offensive  \
 0      NaN                NaN                  NaN                     NaN
 1      NaN                NaN                  NaN                     NaN
 2      NaN                NaN                  NaN                     NaN
 3      NaN                NaN                  NaN                     NaN
 4      NaN                NaN                  NaN                     NaN
 ...    ...                ...                  ...                     ...
 2694   NaN                NaN                  NaN                     NaN
 2695   NaN                NaN                  NaN                     NaN
 2696   NaN                NaN                  NaN                     NaN
 2697   NaN                NaN                  NaN                     NaN
 2698   NaN                NaN                  NaN                     NaN

      ball_recovery_recovery_failure block_offensive carry_end_location  \
 0                               NaN             NaN                NaN
 1                               NaN             NaN                NaN
 2                               NaN             NaN                NaN
 3                               NaN             NaN                NaN
 4                               NaN             NaN                NaN
 ...                             ...             ...                ...
 2694                            NaN             NaN                NaN
 2695                            NaN             NaN                NaN
 2696                            NaN             NaN                NaN
 2697                            NaN             NaN                NaN
 2698                            NaN             NaN                NaN

      clearance_aerial_won clearance_body_part clearance_head  ...  \
 0                     NaN                 NaN            NaN  ...
 1                     NaN                 NaN            NaN  ...
 2                     NaN                 NaN            NaN  ...
 3                     NaN                 NaN            NaN  ...
 4                     NaN                 NaN            NaN  ...
 ...                   ...                 ...            ...  ...
 2694                  NaN                 NaN            NaN  ...
 2695                  NaN                 NaN            NaN  ...
 2696                  NaN                 NaN            NaN  ...
 2697                  NaN                 NaN            NaN  ...
 2698                  NaN                 NaN            NaN  ...

      substitution_outcome substitution_outcome_id   substitution_replacement  \
 0                     NaN                     NaN                        NaN
 1                     NaN                     NaN                        NaN
 2                     NaN                     NaN                        NaN
 3                     NaN                     NaN                        NaN
 4                     NaN                     NaN                        NaN
 ...                   ...                     ...                        ...
 2694             Tactical                   103.0  Jean Thierry Lazare Amani
 2695                  NaN                     NaN                        NaN
 2696                  NaN                     NaN                        NaN
 2697                  NaN                     NaN                        NaN
 2698                  NaN                     NaN                        NaN

      substitution_replacement_id  \
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 ...                          ...
 2694                     23957.0
 2695                         NaN
 2696                         NaN
 2697                         NaN
 2698                         NaN

                                                 tactics           team  \
 0     {'formation': 343, 'lineup': [{'player': {'id'...        Nigeria
 1     {'formation': 433, 'lineup': [{'player': {'id'...  Côte d'Ivoire
 2                                                   NaN        Nigeria
 3                                                   NaN  Côte d'Ivoire
 4                                                   NaN  Côte d'Ivoire
 ...                                                 ...            ...
 2694                                                NaN  Côte d'Ivoire
 2695  {'formation': 343, 'lineup': [{'player': {'id'...        Nigeria
 2696  {'formation': 4231, 'lineup': [{'player': {'id...        Nigeria
 2697  {'formation': 433, 'lineup': [{'player': {'id'...  Côte d'Ivoire
 2698  {'formation': 433, 'lineup': [{'player': {'id'...  Côte d'Ivoire

      team_id     timestamp            type under_pressure
 0        775  00:00:00.000     Starting XI            NaN
 1       3374  00:00:00.000     Starting XI            NaN
 2        775  00:00:00.000      Half Start            NaN
 3       3374  00:00:00.000      Half Start            NaN
 4       3374  00:00:00.000      Half Start            NaN
 ...      ...           ...             ...            ...
 2694    3374  00:46:41.128    Substitution            NaN
 2695     775  00:27:25.263  Tactical Shift            NaN
 2696     775  00:42:35.583  Tactical Shift            NaN
 2697    3374  00:42:45.687  Tactical Shift            NaN
 2698    3374  00:46:53.679  Tactical Shift            NaN

 [2699 rows x 91 columns],
      50_50 ball_receipt_outcome ball_recovery_offensive  \
 0      NaN                  NaN                     NaN
 1      NaN                  NaN                     NaN
 2      NaN                  NaN                     NaN
 3      NaN                  NaN                     NaN
 4      NaN                  NaN                     NaN
 ...    ...                  ...                     ...
 3382   NaN                  NaN                     NaN
 3383   NaN                  NaN                     NaN
 3384   NaN                  NaN                     NaN
 3385   NaN                  NaN                     NaN
 3386   NaN                  NaN                     NaN

      ball_recovery_recovery_failure block_offensive carry_end_location  \
 0                               NaN             NaN                NaN
 1                               NaN             NaN                NaN
 2                               NaN             NaN                NaN
 3                               NaN             NaN                NaN
 4                               NaN             NaN                NaN
 ...                             ...             ...                ...
 3382                            NaN             NaN                NaN
 3383                            NaN             NaN                NaN
 3384                            NaN             NaN                NaN
 3385                            NaN             NaN                NaN
 3386                            NaN             NaN                NaN

      clearance_aerial_won clearance_body_part clearance_head  \
 0                     NaN                 NaN            NaN
 1                     NaN                 NaN            NaN
 2                     NaN                 NaN            NaN
 3                     NaN                 NaN            NaN
 4                     NaN                 NaN            NaN
 ...                   ...                 ...            ...
 3382                  NaN                 NaN            NaN
 3383                  NaN                 NaN            NaN
 3384                  NaN                 NaN            NaN
 3385                  NaN                 NaN            NaN
 3386                  NaN                 NaN            NaN

      clearance_left_foot  ... substitution_outcome substitution_outcome_id  \
 0                    NaN  ...                  NaN                     NaN
 1                    NaN  ...                  NaN                     NaN
 2                    NaN  ...                  NaN                     NaN
 3                    NaN  ...                  NaN                     NaN
 4                    NaN  ...                  NaN                     NaN
 ...                  ...  ...                  ...                     ...
 3382                 NaN  ...                  NaN                     NaN
 3383                 NaN  ...                  NaN                     NaN
 3384                 NaN  ...                  NaN                     NaN
 3385                 NaN  ...                  NaN                     NaN
 3386                 NaN  ...                  NaN                     NaN

      substitution_replacement substitution_replacement_id  \
 0                         NaN                         NaN
 1                         NaN                         NaN
 2                         NaN                         NaN
 3                         NaN                         NaN
 4                         NaN                         NaN
 ...                       ...                         ...
 3382                      NaN                         NaN
 3383                      NaN                         NaN
 3384                      NaN                         NaN
 3385                      NaN                         NaN
 3386                      NaN                         NaN

                                                 tactics          team team_id  \
 0     {'formation': 4411, 'lineup': [{'player': {'id...  South Africa    4976
 1     {'formation': 4231, 'lineup': [{'player': {'id...      Congo DR    4881
 2                                                   NaN  South Africa    4976
 3                                                   NaN      Congo DR    4881
 4                                                   NaN  South Africa    4976
 ...                                                 ...           ...     ...
 3382  {'formation': 4231, 'lineup': [{'player': {'id...      Congo DR    4881
 3383  {'formation': 4231, 'lineup': [{'player': {'id...      Congo DR    4881
 3384                                                NaN  South Africa    4976
 3385                                                NaN      Congo DR    4881
 3386                                                NaN      Congo DR    4881

          timestamp            type under_pressure
 0     00:00:00.000     Starting XI            NaN
 1     00:00:00.000     Starting XI            NaN
 2     00:00:00.000      Half Start            NaN
 3     00:00:00.000      Half Start            NaN
 4     00:00:00.000      Half Start            NaN
 ...            ...             ...            ...
 3382  00:33:20.036  Tactical Shift            NaN
 3383  00:40:20.608  Tactical Shift            NaN
 3384  00:19:50.514           Error            NaN
 3385  00:24:03.836      Player Off            NaN
 3386  00:26:18.651       Player On            NaN

 [3387 rows x 88 columns],
                                                   50_50 ball_receipt_outcome  \
 0                                                   NaN                  NaN
 1                                                   NaN                  NaN
 2                                                   NaN                  NaN
 3                                                   NaN                  NaN
 4                                                   NaN                  NaN
 ...                                                 ...                  ...
 2759  {'outcome': {'id': 3, 'name': 'Success To Team'}}                  NaN
 2760                                                NaN                  NaN
 2761                                                NaN                  NaN
 2762                                                NaN                  NaN
 2763                                                NaN                  NaN

      ball_recovery_recovery_failure carry_end_location clearance_aerial_won  \
 0                               NaN                NaN                  NaN
 1                               NaN                NaN                  NaN
 2                               NaN                NaN                  NaN
 3                               NaN                NaN                  NaN
 4                               NaN                NaN                  NaN
 ...                             ...                ...                  ...
 2759                            NaN                NaN                  NaN
 2760                            NaN                NaN                  NaN
 2761                            NaN                NaN                  NaN
 2762                            NaN                NaN                  NaN
 2763                            NaN                NaN                  NaN

      clearance_body_part clearance_head clearance_left_foot  \
 0                    NaN            NaN                 NaN
 1                    NaN            NaN                 NaN
 2                    NaN            NaN                 NaN
 3                    NaN            NaN                 NaN
 4                    NaN            NaN                 NaN
 ...                  ...            ...                 ...
 2759                 NaN            NaN                 NaN
 2760                 NaN            NaN                 NaN
 2761                 NaN            NaN                 NaN
 2762                 NaN            NaN                 NaN
 2763                 NaN            NaN                 NaN

      clearance_right_foot counterpress  ... substitution_outcome  \
 0                     NaN          NaN  ...                  NaN
 1                     NaN          NaN  ...                  NaN
 2                     NaN          NaN  ...                  NaN
 3                     NaN          NaN  ...                  NaN
 4                     NaN          NaN  ...                  NaN
 ...                   ...          ...  ...                  ...
 2759                  NaN         True  ...                  NaN
 2760                  NaN          NaN  ...                  NaN
 2761                  NaN          NaN  ...                  NaN
 2762                  NaN          NaN  ...                  NaN
 2763                  NaN          NaN  ...                  NaN

      substitution_outcome_id substitution_replacement  \
 0                        NaN                      NaN
 1                        NaN                      NaN
 2                        NaN                      NaN
 3                        NaN                      NaN
 4                        NaN                      NaN
 ...                      ...                      ...
 2759                     NaN                      NaN
 2760                     NaN                      NaN
 2761                     NaN                      NaN
 2762                     NaN                      NaN
 2763                     NaN                      NaN

      substitution_replacement_id  \
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 ...                          ...
 2759                         NaN
 2760                         NaN
 2761                         NaN
 2762                         NaN
 2763                         NaN

                                                 tactics           team  \
 0     {'formation': 433, 'lineup': [{'player': {'id'...  Côte d'Ivoire
 1     {'formation': 4231, 'lineup': [{'player': {'id...       Congo DR
 2                                                   NaN  Côte d'Ivoire
 3                                                   NaN       Congo DR
 4                                                   NaN  Côte d'Ivoire
 ...                                                 ...            ...
 2759                                                NaN  Côte d'Ivoire
 2760  {'formation': 4231, 'lineup': [{'player': {'id...  Côte d'Ivoire
 2761  {'formation': 442, 'lineup': [{'player': {'id'...       Congo DR
 2762  {'formation': 4231, 'lineup': [{'player': {'id...  Côte d'Ivoire
 2763                                                NaN       Congo DR

      team_id     timestamp            type under_pressure
 0       3374  00:00:00.000     Starting XI            NaN
 1       4881  00:00:00.000     Starting XI            NaN
 2       3374  00:00:00.000      Half Start            NaN
 3       4881  00:00:00.000      Half Start            NaN
 4       3374  00:00:00.000      Half Start            NaN
 ...      ...           ...             ...            ...
 2759    3374  00:39:09.812           50/50           True
 2760    3374  00:16:14.661  Tactical Shift            NaN
 2761    4881  00:24:08.866  Tactical Shift            NaN
 2762    3374  00:44:50.300  Tactical Shift            NaN
 2763    4881  00:25:33.069           Error            NaN

 [2764 rows x 85 columns],
      50_50 ball_receipt_outcome ball_recovery_recovery_failure  \
 0      NaN                  NaN                            NaN
 1      NaN                  NaN                            NaN
 2      NaN                  NaN                            NaN
 3      NaN                  NaN                            NaN
 4      NaN                  NaN                            NaN
 ...    ...                  ...                            ...
 3880   NaN                  NaN                            NaN
 3881   NaN                  NaN                            NaN
 3882   NaN                  NaN                            NaN
 3883   NaN                  NaN                            NaN
 3884   NaN                  NaN                            NaN

      block_deflection block_offensive carry_end_location clearance_aerial_won  \
 0                 NaN             NaN                NaN                  NaN
 1                 NaN             NaN                NaN                  NaN
 2                 NaN             NaN                NaN                  NaN
 3                 NaN             NaN                NaN                  NaN
 4                 NaN             NaN                NaN                  NaN
 ...               ...             ...                ...                  ...
 3880              NaN             NaN                NaN                  NaN
 3881              NaN             NaN                NaN                  NaN
 3882              NaN             NaN                NaN                  NaN
 3883              NaN             NaN                NaN                  NaN
 3884              NaN             NaN                NaN                  NaN

      clearance_body_part clearance_head clearance_left_foot  ...  \
 0                    NaN            NaN                 NaN  ...
 1                    NaN            NaN                 NaN  ...
 2                    NaN            NaN                 NaN  ...
 3                    NaN            NaN                 NaN  ...
 4                    NaN            NaN                 NaN  ...
 ...                  ...            ...                 ...  ...
 3880                 NaN            NaN                 NaN  ...
 3881                 NaN            NaN                 NaN  ...
 3882                 NaN            NaN                 NaN  ...
 3883                 NaN            NaN                 NaN  ...
 3884                 NaN            NaN                 NaN  ...

      substitution_outcome substitution_outcome_id substitution_replacement  \
 0                     NaN                     NaN                      NaN
 1                     NaN                     NaN                      NaN
 2                     NaN                     NaN                      NaN

In [10]:
import pandas as pd
df = pd.concat(all_matches)

In [11]:
df.player.unique()

array([nan, 'Ademola Lookman', 'William Troost-Ekong',
       'Calvin Bassey Ughelumba', 'Oluwasemilogo Adesewo Ibidapo Ajayi',
       'Yahia Fofana', 'Obite Evan Ndicka', 'Ghislain Konan',
       'Odilon Kossonou', 'Simon Adingra', 'Zaidu Sanusi', 'Alex Iwobi',
       'Victor James Osimhen', 'Samuel Chimerenka Chukwueze',
       'Temitayo Olufisayo Olaoluwa Aina', 'Frank Onyeka',
       'Jean Michaël Seri', 'Serge Aurier', 'Stanley Bobo Nwabali',
       'Seko Fofana', 'Max-Alain Gradel', 'Franck Yannick Kessié',
       'Sébastien Haller', 'Moses Daddy-Ajala Simon',
       'Wilfried Stephane Singo', 'Oumar Diakité',
       'Kelechi Promise Iheanacho', 'Alhassan Yusuf', 'Joe Aribo',
       'Ibrahim Sangaré', 'Terem Igobor Moffi', 'Jean-Philippe Krasso',
       'Jean Thierry Lazare Amani', 'Grady Diangana',
       'Samuel Moutoussamy', 'Khuliso Johnson Mudau',
       'Simon Bokote Banza', 'Nkosinathi Sibisi', 'Ronwen Williams',
       'Siyanda Xulu', 'Evidence Makgopa', 'Teboho Mokoena',
       "Sphephelo S''Miso Sithole", 'Themba Zwane',
       'Mihlali Samson Mayambela', 'Aubrey Maphosa Modiba',
       'Silas Katompa Mvumpa', 'Dylan Batubinsika', 'Joris Kayembe Ditu',
       "Théo Bongonda Mbul''Ofeko Batombo", 'Brian Jephte Bayeye',
       'Aaron Tshibola', 'Chancel Mbemba Mangulu', 'Dimitry Bertaud',
       'Thapelo James Morena', 'Meschak Elia', 'Omenuke Mfulu',
       'Thabang Amod Monare', 'Oswin Reagan Appollis', 'Yoane Wissa',
       'Terrence Mashego', 'Fiston Kalala Mayele', 'Cédric Bakambu',
       'Zakhele Lerato Lepasa', 'Henoc Inonga Baka', 'Arthur Masuaku',
       'Gaël Kakuta', 'Willy Boly', 'Lionel Mpasi-Nzau',
       'Gedeon Kalulu Kyatengwa', 'Charles Pickel', 'Jonathan Bamba',
       'Jeremie Boga', 'Mothobi Mvala', 'Bright Osayi-Samuel',
       'Gomolemo Grant Kekana', 'Percy Tau', 'Kenneth Josiah Omeruo',
       'Habibou Mouhamadou Diallo', 'Abdou Diallo', 'Lamine Camara',
       'Ismail Jakobs', 'Moussa Niakhate', 'Pape Matar Sarr',
       'Kalidou Koulibaly', 'Krépin Diatta', 'Sadio Mané',
       'Edouard Mendy', 'Ismaïla Sarr', 'Nicolas Pépé', 'Nicolas Jackson',
       'Christian Kouamé', 'Idrissa Gueye', 'Iliman Ndiaye',
       'Cheikh Ahmadou Bamba Mbacke Dieng', 'Mohamed Bayo', 'Mory Konaté',
       'Mouctar Diakhaby', 'Amadou Diawara', 'Issiaga Sylla',
       'Julian Jeanvier', 'Ibrahim Diakité', 'Aguibou Camara',
       'Morgan Guilavogui', 'Jesús Lázaro Owono Ngua Akeng',
       'Ibán Salvador Edu', 'Jannick Buyla Sam', 'Sekou Oumar Sylla',
       'Esteban Obiang Obono', 'Carlos Akapo Martínez', 'Ibrahim Kone',
       'Federico Bikoro Akieme Nchama', 'Pablo Ganet Cómitre',
       'Basilio Ndong Owono Nchamaaa', 'Saúl Basilio Coco-Bassey Oubiña',
       'Emilio Nsue López', 'José Ndong Machín Dicombo',
       'Serhou Guirassy', 'François Kamano', 'Naby Deco Keïta',
       'Luis Miguel Nlavo Asue', 'Lassine Sinayoko', 'Sikou Niakate',
       'Falaye Sacko', 'Kamory Doumbia', 'Lassana Coulibaly',
       'Diadie Samassekou', 'Hamari Traoré', 'Djigui Diarra',
       'Boubakar Kouyate', 'Adama Traoré', 'Amadou Haïdara',
       'Fousseni Diabaté', 'Nene Dorgeles', 'Boubacar Traore',
       'Mamadou Fofana', 'Yves Bissouma', 'Ibrahim Sissoko',
       'Jovane Eduardo Borges Cabral', 'Roberto Lopes', 'Logan Costa',
       'Kenny Rocha Santos', 'Jamiro Gregory Monteiro Alvarenga',
       'Steven Moreira', 'Kevin Lenini Gonçalves Pereira de Pina',
       'João Paulo Moreira Fernandes', 'Ryan Isaac Mendes da Graça',
       'Josimar José Évora Dias', 'Garry Mendes Rodrigues',
       'Willy Afonso Semedo Johnson', 'Erickson Patrick Correia Andrade',
       'Thapelo Maseko', 'Tiago Manuel Dias Correia', 'Laros Duarte',
       'Jayden Adams', 'Gilson Benchimol Tavares', 'Nyiko Mobbie',
       'Bryan Silva Teixera', 'Mohamed Camara', 'Bertrand Isidore Traoré',
       'Ibrahim Blati Touré', 'Ismahila Ouédraogo', 'Steeve Yago',
       'Mohamed Konaté', 'Abdoul Fessal Tapsoba', 'Issoufou Dayo',
       'Issa Kabore', 'Gustavo Fabrice Sangaré', 'Edmond Fayçal Tapsoba',
       'Kouakou Herve Koffi', 'Adamo Nagalo', 'Cédric Badolo',
       'Sacha Jordan Bansé', 'Sekou Koita',
       'Dango Aboubacar Faissal Ouattara', 'Stephane Aziz Ki',
       'Abdoulaye Touré', 'Facinet Conte', 'Antoine Conte',
       'Signori Dominique Nymi António', 'Eddie Marcos Melo Afonso',
       'Kialonda Gaspar', 'Alfredo Kulembe Ribeiro',
       'Deivi Miguel Vieira', 'Manuel Luís da Silva Cafumana',
       'Augusto de Jesus Corte Real Carneiro', 'Jonathan Buatu Mananga',
       'Valdomiro Tualungo Paulo Lameiras',
       'Cristóvão Paciência Mabululo', 'Jacinto Muondo Dala',
       'Ambrosini Antonio Cabaça Salvador',
       'Bruno Lourenço Pinto de Almeida Paz',
       'Zito André Sebastião Luvumbo', 'Jérémy Bela',
       'Felicio Mendes Joao Milson', 'Paul Onuachu', 'Ivan Kamberipa',
       'Ngero Kaanjuka Katua', 'Lloyd Junior Kazapua', 'Lubeni Haukongo',
       'Kennedy Amutenya', 'Bethuel Muzeu', 'Deon Hotto Kavendji',
       'Adilson Cipriano da Cruz', 'Aprocious Petrus', 'Riaan Hanamub',
       'Prins Menelik Tjiueza', 'Peter Shalulile', 'Absalom Iimbondi',
       'Petrus Shitembi', 'Ananias Gebhardt', 'Uetuuru Kambato',
       'Manuel Keliano', 'Sofyan Amrabat', 'Nayef Aguerd', 'Romain Saïss',
       'Noussair Mazraoui', 'Achraf Hakimi Mouh', 'Azzedine Ounahi',
       'Selim Amallah', 'Amine Adli', 'Yassine Bounou',
       'Abdessamad Ezzalzouli', 'Youssef En-Nesyri', 'Ismael Saibari',
       'Amine Harit', 'Yahia Attiyat allah', 'Ayoub El Kaabi',
       'Babacar Niasse', 'Bodda Mouhsine', 'Hemeya Tanjy', 'Khadim Diaw',
       'Omaré Gassama', 'Ibrahima Keita', 'El Hacen Houeibib',
       'Lamine Ba', 'Souleymane Anne', 'Sidi Bouna Sidi Amar',
       'Deroy Duarte', 'Aboubakary Koita', 'Guessouma Fofana',
       'Pape Ibnou Bâ', 'Yassin Cheikh El Welly', 'El-Hadji Ba',
       'Aboubakar Kamara', 'Ahmed Sayed',
       'Ahmed Elsayed Ali Elsayed Hegazy', 'Marwan Attia Fahim Ghallab',
       'Mostafa Mohamed Ahmed Abdallah', 'Hamdi Fathi',
       'Ahmed Mohamed Abo El Fotouh Mohamed',
       'Mohamed Naser Elsayed Elneny', 'Mahmoud Ibrahim Hassan',
       'Mohamed Hany Gamal Eldemerdash', 'Mohamed Abougabal',
       'Mohamed Abdel Monem', 'Mohamed Hamdy Sharaf', 'Mahmoud Hamada',
       'Omar Marmoush', 'Mostafa Fathi', 'Omar Kamal Abdel Wahed',
       'Mohanad Mostafa Lasheen', 'Jules Olivier Ntcham',
       'André-Frank Zambo Anguissa', 'Jean-Charles Castelletto',
       'Nicolas Moumi Ngamaleu', 'Karl Brillant Toko Ekambi',
       'Oumar Gonzalez', 'Christopher Wooh', 'Joseph Fabrice Ondoa Ebogo',
       'Nouhou Tolo', 'Frank Magri', 'Georges-Kévin Nkoudou Mbida',
       'Francis Odinaka Uzoho', 'Vincent Paté Aboubakar',
       'Enzo Gianni Tchato Mbiayi', 'Faris Pemi Moumbagna', 'Denis Odoi',
       'Alexander Djiku', 'Richard Ofori Antwi', 'Mohamed Salisu',
       'Majeed Ashimeru', 'Mohamed El Sayed Mohamed El Shenawy Gomaa',
       'Jordan Ayew', 'Emam Ashour Metwally Abdelghany',
       'Salis Abdul Samed', 'Iñaki Williams Arthuer', 'Mohamed Salah',
       'Antoine Semenyo', 'Gideon Mensah', 'Mohammed Kudus',
       'Iddrisu Baba Mohammed', 'Osman Bukari', 'Elisha Owusu',
       'Joseph Paintsil', 'Alejandro Balboa Bandeira',
       'Santiago Eneme Bocari', 'José Nabil Onva Adjugu', 'Alfons Amade',
       'Witiness Chimoio João Quembo', 'Domingos João Macandza',
       'Edson André Sitoe', 'Ernan Alberto Siluane',
       'Edmilson Gabriel Dove', 'Stanley Ratifo',
       'Gildo Lourenço Vilanculos', 'Reinildo Isnard Mandava',
       'Ricardo Martins Guimarães', 'Elias Gaspar Pelembe',
       'Bruno Alberto Langa', 'Clésio Bauque', 'Pachoio Lau Há King',
       'Amade Momade', 'Feliciano João Jone', 'Ahmed Hassan Mahgoub',
       'Ransford Königsdörffer', 'Ernest Appiah Nuamah',
       'André Ayew Pelé', 'Yunis Abdelhamid', 'Sofiane Boufal',
       'Lubambo Musonda', 'Emmanuel Justine Rabby Banda', 'Hakim Ziyech',
       'Tresford Lawrence Mulenga', 'Stopilla Sunzu', 'Frankie Musonda',
       'Tandi Mwape', 'Kennedy Musonda', 'Lameck Banda',
       'Edward Chilufya', 'Miguel Changa Chaiwa', 'Patson Daka',
       'Amir Richardson', 'Kings Kangwa', 'Fashion Sakala',
       'Tarik Tissoudali', 'Cletous Chama', 'Bilal El Khannous',
       'Mbwana Ally Samatta', 'Faisal Salum Abdalla', 'Lusajo Mwaikenda',
       'Bakari Nondo Mwamnyeto', 'Ibrahim Abdallah Hamad',
       'Mohamed Hussein Mohamed', 'Haji Mnoga', 'Simon Happygod Msuva',
       'Novatus Dismas Miroshi', 'Himid Mao Mkami', 'Aishi Manula',
       'Mzamiru Yassin', 'Morice Michael Abraham', "Charles M'Mombwa",
       'Denis Kibu', 'Youssoufou Niakaté', 'Aliou Dieng', 'Moussa Diarra',
       'Amadou Dante', 'Vetunuavi Charles Hambira', 'Marcel Papama',
       'Wajdi Kechrida', 'Yassine Meriah', 'Montassar Omar Talbi',
       'Aïssa Bilal Laïdouni', 'Ellyes Joris Skhiri', 'Seifeddine Jaziri',
       'Mohamed Elias Achouri', 'Hamza Rafia', 'Ali Abdi',
       'Bechir Ben Said', 'Anis Ben Slimane', 'Youssef Msakni',
       'Sayfallah Ltaief', 'Naïm Sliti', 'Haythem Jouini',
       'Mohamed Ali Ben Romdhane', 'Baghdad Bounedjah', 'Houssem Aouar',
       'Ramiz Larbi Zerrouki', 'Hichem Boudaoui', 'Aïssa Mandi',
       'Mohamed Amine Tougai', 'Rayan Aït Nouri',
       'Mohamed El Amine Amoura', 'Youcef Atal', 'Mohamed Dellahi Yali',
       'Anthony Louis Mandréa', 'Adam Ounas', 'Idrissa Thiam',
       'Riyad Mahrez', 'Nabil Bentaleb', 'Mohamed Youcef Belaïli',
       'Islam Slimani', 'Bakari Camara', 'Kévin Daniel Van Den Kerkhof',
       'Joaquim Marcos Cunga Balanga', 'Abdoul Razack Guiebre',
       'Djibril Cheick Ouattara', 'Boureima Hassane Bandé', 'Ali Sowe',
       'Musa Barrow', 'Yusupha Bobb', 'Omar Colley', 'Baboucarr Gaye',
       'Alasana Manneh', 'Jacob Mendy', 'Yankuba Minteh', 'Ablie Jallow',
       'Muhammed Sanneh', 'James Gomez', 'Darlin Zidane Yongwa Ngameni',
       'Bubacarr Sanneh', 'Alieu Fadera', 'Assan Ceesay',
       'Olivier Michel Kemen', 'Ebrima Colley', 'Harold Moukoudi',
       'Saidy Janko', 'Nampalys Mendy', 'Abdoulaye Seck', 'Pape Gueye',
       'Saidou Sow', 'Mohamed Aly Camara', 'Moriba Kourouma Kourouma',
       'Cheikhou Kouyaté', 'Idrissa Gana Gueye', 'Seydouba Cisse',
       'Karim Cissé', 'Fodé Ballo Touré',
       'Edilson Alberto Monteiro Sanches Borges',
       'Dylan Tavares dos Santos', 'Carlos Miguel Pereira Fernandes',
       'Mahmoud Abdul Monem Abdelhamid Soliman',
       'Infren Da Conceição David Matola',
       'Ivane Carminio Francisco Urrubal', 'Geny Cipriano Catamo',
       'Alidu Seidu', 'Daniel Amartey', 'Shaquille Momad Nangy',
       'João José Jone Bonde', 'Janio Bikel Figueiredo Silva',
       'Famana Quizera', 'Zinho Gano', 'Houboulang Mendes',
       'Jonas Asvedo Mendes', 'Fernando de Lacerda Gomes',
       'Edgar Miguel Ié', 'Opa Sangante', 'Eulânio Ângelo Chipela Gomes',
       'Euciodálcio Gomes', 'Carlos Mendes Gomes', 'Franculino Gluda Djú',
       'Marciano Sanca Tchami', 'Raphael Onyedika', 'José Correia',
       'Fali Candé', 'Alfa Semedo Esteves', 'Chidozie Collins Awaziem',
       'José Antonio Miranda Boacho', 'Karim Konaté',
       'Juan José Óscar Siafá Etoha', 'Ryan Nyambe', 'Joslin Kamatuka',
       'Wendell Rudath', 'Kelvin Kapumbu', 'Roderick Kabwe',
       'Benedict Chepeshi', 'Mudathiri Yahya', 'Mohamed Chibi',
       'Bassem Srarfi', 'Nouh Mohamed El Abd', 'Yacoub Aly Abeid',
       'Núrio Domingos Matias Fortuna', 'Souleymane Doukara',
       'Ramy Bensebaini', 'Adama Guira', 'Sofiane Feghouli',
       'Fares Chaïbi', 'Dramane Salou', 'Yacouba Nasser Djiga',
       'Noah Sonko-Sundberg', 'Ebrima Darboe', 'Hamza Barry',
       'José Kanté Martínez', 'Muhammed Badamosi', 'Yvan Neyou Noupa',
       'André Onana', 'Junior Tchamadeu', 'Ousmane Diomande',
       'Moreto Moro Cassamã', 'Jefferson Anilson Silva Encada',
       'Marcelo Amado Djaló Taritolay', 'Manconi Soriano Mané',
       'Mama Samba Baldé', 'Mauro Daniel Rodrigues Teixeira',
       'Ouparine Djoco', 'Marvin José Anieboh Pallaruelo',
       'Carlos Manuel Cardoso Mané', 'Noé Ela Mangue', 'Larry Bwalya',
       'Tarryn Allarakhia', 'Ali Maâloul', 'Taha Yassine Khenissi',
       'Mamady Alex Bangré', 'Oumar Ngom', 'Aboubacar Traoré',
       'Ismael Bennacer', 'Loide António Augusto', 'Ibou Touray',
       'Ebou Adams', 'Pathé Ismaël Ciss', 'Abdulia Sanyang',
       'Idrissa Doumbia'], dtype=object)

In [12]:
df = df[df['player'] == 'Jonathan Bamba']

In [13]:
df.head()

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,shot_redirect,goalkeeper_shot_saved_to_post,shot_saved_to_post,pass_straight,shot_open_goal,goalkeeper_punched_out,goalkeeper_shot_saved_off_target,shot_saved_off_target,player_off_permanent,block_save_block
662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.shape

(190, 111)